version: '3.7'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mysql
    links:
      - mysql
